---
title: "Final Project - Pratical Machine Learning" 
subtitle: "Analising and modeling Human Active Recognition data"
author: "Matheus Cardoso"
date: "May 28, 2020"
output: 
  html_document: 
    fig_caption: yes
    highlight: zenburn
    keep_md: yes
    theme: simplex
    toc: yes
    toc_float: yes
    number_sections: yes
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, include = TRUE, cache = TRUE, warning = FALSE, message = FALSE)
```

# Introdução

Nesse documento será feita uma análise explotarória dos dados advindos do software `attila`.

# Métodos

## Processamento dos dados

```{r load_data}
library(tidyverse)
library(magrittr)

cdr <- read_rds("./data/binary/isaura_compressed.rds")
cdr %<>% mutate(type = factor(case_when(
                        str_detect(file, "Final") ~ "final",
                        str_detect(file, "Initial") ~ "initial"))) %>% 
         ungroup() %>% 
         group_by(file) %>% 
         mutate(cdrp = quantity/sum(quantity)) %>% 
         select(cdr3, type, cdrp, everything()) %>% 
         arrange(-cdrp, -quantity) %>% 
         ungroup()

dim(cdr)
names(cdr)
knitr::kable(head(cdr))
summary(cdr)
```

## Análise Exploratória

### Isolando apenas as sequências CDR3 enriquecidas

```{r eda1}
cdr %>%
        ungroup() %>% 
        arrange(-cdrp, type, file) %>% 
        filter(quantity > 1) %>% 
        filter(type == "final") -> cdr_final

cdr_final %>% 
                filter(quantity > 1) %>% 
                group_by(file) %>% 
                slice_head(n = 1) -> cdr_enriched

# library(GGally)
# cdr_enriched %<>%
#                 select(cdr3:SSF_Sheet, aromatic:file)
# 
# cdr_enriched %>%
#                 ungroup() %>% 
#                 select(-file) %>% 
#                 ggpairs(aes(alpha = 0.4))
```

```{r eda2}
cdr_final %>% 
             ungroup() %>% 
             select(!c(cdr3, type, file, invalid)) -> cdr_final_pca

pca_result <- prcomp(cdr_final_pca, center = T, scale. = T)
summary(pca_result)

plot(pca_result$x[,1], pca_result$x[,2])
cdr_final_pca

cdr_final %>% 
              group_by(file) %>% 
              arrange(-cdrp) %>% 
              slice_head(n = 1) %>% 
              ungroup() %>% 
              select(!c(cdr3, type, file, invalid)) %>% 
              arrange(-cdrp) -> a

# in this line we remove all collumns that have variance equal to 0
# Doing this, we can apply a pca to the dataframe without erros
# credit goes to: https://stackoverflow.com/a/40317343
a <- select(a, !c(which(apply(a, 2, var)==0)))
pca_a <- prcomp(a, center = T, scale. = T)
summary(pca_a)
plot(pca_a$x[,1], pca_a$x[,2])

ggplot(as_tibble(pca_a$x)) +
  geom_point(aes(PC1, PC2))

pca_a$x
str(pca_a)

# pca_cdr_result <- cdr %>%
#                         select(!c(cdr3, type, file, invalid)) %>% 
#                         prcomp(center = T, scale. = T)
# summary(pca_cdr_result)
```

```{r eda3}
cdr_final %>% 
              group_by(file) %>% 
              arrange(-cdrp) %>% 
              slice_head(n = 10) %>% 
              ungroup() %>% 
              select(!c(cdr3, type, file, invalid)) %>% 
              arrange(-cdrp) -> b

b <- select(b, !c(which(apply(b, 2, var)==0)))
b
pca_b <- prcomp(b, center = T, scale. = T)
summary(pca_b)
plot(pca_b$x[,1], pca_b$x[,2])

ggplot(as_tibble(pca_b$x)) +
  geom_point(aes(PC1, PC2))

summary(pca_b)
```

```{r eda4}
summary(cdr$quantity)
cdr %>% 
        filter(quantity >= 100) -> a
a

ggplot(a) +
  geom_density(aes(quantity))

ggplot(cdr) +
  geom_bar(aes(quantity)) +
  xlim(0, 30)

ggplot(cdr) +
  geom_histogram(aes(quantity)) +
  xlim(0, 300)

ggplot(cdr) +
  geom_density(aes(quantity), fill = "lightblue") +
  xlim(0, 300)

quantile(cdr$quantity)

dim(cdr)
cdr %>% filter(quantity >= 1E3) %>% dim()
cdr %>% filter(quantity >= 1E4) %>% dim()
cdr %>% filter(quantity >= 1E5) %>% dim()

cdr %>% filter(quantity >= 1E3) -> b
b %>% group_by(type) %>% summarise(total = n())
b %>% group_by(type) %>% summarise(quantile = quantile(cdrp)) -> b_quantiles
b_quantiles <- add_column(b_quantiles, quantiles = rep(attr(quantile(b$quantity), "names"), 2))
knitr::kable(b_quantiles)
```

# Resultados

# Conclusão
